"_______________________________________________________________________
" This file is included with the Vim color scheme generated by
" Color Scheme Exporter
"_______________________________________________________________________

"_______________________________________________________________________
" COLOR DEFINITONS
"_______________________________________________________________________

"-----------------------------------------------------------------------
" GUI Colors
"-----------------------------------------------------------------------

let gui_bg__norm = '#BG__NORM'
let gui_fg__norm = '#FG__NORM'

let gui_blk_norm = '#BLK_NORM'
let gui_red_norm = '#RED_NORM'
let gui_grn_norm = '#GRN_NORM'
let gui_yel_norm = '#YEL_NORM'
let gui_blu_norm = '#BLU_NORM'
let gui_mag_norm = '#VIO_NORM'
let gui_cya_norm = '#CYA_NORM'
let gui_wht_norm = '#WHT_NORM'

let gui_blk_bold = '#BLK_BOLD
let gui_red_bold = '#RED_BOLD'
let gui_grn_bold = '#GRN_BOLD'
let gui_yel_bold = '#YEL_BOLD'
let gui_blu_bold = '#BLU_BOLD'
let gui_mag_bold = '#VIO_BOLD'
let gui_cya_bold = '#CYA_BOLD'
let gui_wht_bold = '#WHT_BOLD'

"-----------------------------------------------------------------------
" CLI Colors
"-----------------------------------------------------------------------
let cli_bg__norm = 'BG__BOLD_CLI'
let cli_fg__norm = 'FG__BOLD_CLI'

let cli_blk_norm = 'BLK_NORM_CLI'
let cli_red_norm = 'RED_NORM_CLI'
let cli_grn_norm = 'GRN_NORM_CLI'
let cli_yel_norm = 'YEL_NORM_CLI'
let cli_blu_norm = 'BLU_NORM_CLI'
let cli_mag_norm = 'VIO_NORM_CLI'
let cli_cya_norm = 'CYA_NORM_CLI'
let cli_wht_norm = 'WHT_NORM_CLI'

let cli_blk_bold = 'BLK_BOLD_CLI'
let cli_red_bold = 'RED_BOLD_CLI'
let cli_grn_bold = 'GRN_BOLD_CLI'
let cli_yel_bold = 'YEL_BOLD_CLI'
let cli_blu_bold = 'BLU_BOLD_CLI'
let cli_mag_bold = 'VIO_BOLD_CLI'
let cli_cya_bold = 'CYA_BOLD_CLI'
let cli_wht_bold = 'WHT_BOLD_CLI'

"_______________________________________________________________________
" COLOR SCHEME DEFINITION
"_______________________________________________________________________
set background=IS_DARK
hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = 'NAME'

" File containing the highlight group configurations
source ~/.vim/colors/flux-bunny-base.vim