"_______________________________________________________________________
" This file is included with the Vim color scheme generated by
" Color Scheme Exporter
"_______________________________________________________________________

"_______________________________________________________________________
" COLOR SCHEME DEFINITION
"_______________________________________________________________________
set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = 'theme-name'

"_______________________________________________________________________
" COLOR DEFINITONS
"_______________________________________________________________________

"-----------------------------------------------------------------------
" GUI Colors
"-----------------------------------------------------------------------

let gui_bg__norm = '#262626'
let gui_fg__norm = '#c6c6c6'

let gui_blk_norm = '#202020'
let gui_red_norm = '#af5f5f'
let gui_grn_norm = '#5faf5f'
let gui_yel_norm = '#afaf5f'
let gui_blu_norm = '#5f5faf'
let gui_mag_norm = '#af5faf'
let gui_cya_norm = '#5fafaf'
let gui_wht_norm = '#afafaf'

let gui_bg__bold = '#1c1c1c'
let gui_fg__bold = '#bcbcbc'

let gui_blk_bold = '#878787'
let gui_red_bold = '#d75f5f'
let gui_grn_bold = '#5fd75f'
let gui_yel_bold = '#d7d75f'
let gui_blu_bold = '#5f5fd7'
let gui_mag_bold = '#d75fd7'
let gui_cya_bold = '#5fd7d7'
let gui_wht_bold = '#d7d7d7'

"-----------------------------------------------------------------------
" CLI Colors
"-----------------------------------------------------------------------
let cli_bg__norm = '235'
let cli_fg__norm = '251'

let cli_blk_norm = '234'
let cli_red_norm = '131'
let cli_grn_norm = '71'
let cli_yel_norm = '143'
let cli_blu_norm = '61'
let cli_mag_norm = '133'
let cli_cya_norm = '73'
let cli_wht_norm = '145'

let cli_bg__bold = '234'
let cli_fg__bold = '250'

let cli_blk_bold = '102'
let cli_red_bold = '167'
let cli_grn_bold = '77'
let cli_yel_bold = '185'
let cli_blu_bold = '62'
let cli_mag_bold = '170'
let cli_cya_bold = '80'
let cli_wht_bold = '188'

" File containing the highlight group configurations
source ~/.vim/colors/flux-bunny-base.vim